
name: 'ðŸŽ‰ Feature Request / åŠŸèƒ½å»ºè®®'
title: "[Feature]"
description: Submit a suggestion to help us improve. / æäº¤å»ºè®®å¸®åŠ©æˆ‘ä»¬æ”¹è¿›ã€‚
labels: [ "enhancement" ]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to suggest a new feature! Please explain your idea clearly and accurately. / æ„Ÿè°¢æ‚¨æŠ½å‡ºæ—¶é—´æå‡ºæ–°åŠŸèƒ½å»ºè®®ï¼Œè¯·å‡†ç¡®è§£é‡Šæ‚¨çš„æƒ³æ³•ã€‚

  - type: textarea
    attributes:
      label: Description / æè¿°
      description: Please describe the feature you want to be added in detail. / è¯·è¯¦ç»†æè¿°æ‚¨å¸Œæœ›æ·»åŠ çš„åŠŸèƒ½ã€‚

  - type: textarea
    attributes:
      label: Use Case / ä½¿ç”¨åœºæ™¯
      description: Please describe the use case for this feature. / è¯·æè¿°è¿™ä¸ªåŠŸèƒ½çš„ä½¿ç”¨åœºæ™¯ã€‚

  - type: checkboxes
    attributes:
      label: Willing to Submit PR? / æ˜¯å¦æ„¿æ„æäº¤PRï¼Ÿ
      description: >
        This is not required, but if you are willing to submit a PR to implement this feature, it would be greatly appreciated! / è¿™ä¸æ˜¯å¿…éœ€çš„ï¼Œä½†å¦‚æžœæ‚¨æ„¿æ„æäº¤ PR æ¥å®žçŽ°è¿™ä¸ªåŠŸèƒ½ï¼Œæˆ‘ä»¬å°†ä¸èƒœæ„Ÿæ¿€ï¼
      options:
        - label: Yes, I am willing to submit a PR. / æ˜¯çš„ï¼Œæˆ‘æ„¿æ„æäº¤ PRã€‚

  - type: checkboxes
    attributes:
      label: Code of Conduct
      options:
        - label: >
            I have read and agree to abide by the project's [Code of Conduct](https://docs.github.com/zh/site-policy/github-terms/github-community-code-of-conduct). /
          required: true

  - type: markdown
    attributes:
      value: "Thank you for filling out our form!"